name: update-sub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download subconverter
        run: |
          git clone https://github.com/tindy2013/subconverter.git
          cd subconverter

      - name: Generate subscription
        run: |
          mkdir -p output
          
          URLS=$(paste -sd '|' sources.txt)

          curl -L "http://sub.id9.cc/sub?target=clash&url=$URLS" \
          -o output.yaml

          ls -la
          cat output.yaml || true

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add output.yaml

          git diff --cached --quiet && echo "No changes" || git commit -m "update sub"

          git push
