name: update-sub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate subscription
        run: |
          rm -f output.yaml

          URLS=$(paste -sd '|' sources.txt)

          curl -L "http://sub.id9.cc/sub?target=clash&url=$URLS" \
          -o output.yaml

          ls -lh output.yaml
          cat output.yaml | head

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add output.yaml

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "update subscription"

          git push
