name: update-sub

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download subscriptions
        run: |
          cat sources.txt > urls.txt

      - name: Build merged subscription
        run: |
          rm -f output.yaml
          while read line
          do
            curl -L --max-time 20 "$line" >> output.yaml || true
            echo "" >> output.yaml
          done < urls.txt

      - name: Commit files
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@example.com"

          git add output.yaml
          git commit -m "update" || echo "no changes"
          git push
